//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TablCHast_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Дом.
    /// </summary>
    // *** Start programmer edit section *** (Дом CustomAttributes)

    // *** End programmer edit section *** (Дом CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДомE", new string[] {
            "Номер as \'Номер\'"})]
    [View("ДомL", new string[] {
            "Номер as \'Номер\'"})]
    public class Дом : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомер;
        
        // *** Start programmer edit section *** (Дом CustomMembers)

        // *** End programmer edit section *** (Дом CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Дом.Номер CustomAttributes)

        // *** End programmer edit section *** (Дом.Номер CustomAttributes)
        [StrLen(255)]
        public virtual string Номер
        {
            get
            {
                // *** Start programmer edit section *** (Дом.Номер Get start)

                // *** End programmer edit section *** (Дом.Номер Get start)
                string result = this.fНомер;
                // *** Start programmer edit section *** (Дом.Номер Get end)

                // *** End programmer edit section *** (Дом.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Дом.Номер Set start)

                // *** End programmer edit section *** (Дом.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Дом.Номер Set end)

                // *** End programmer edit section *** (Дом.Номер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДомE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДомE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДомE", typeof(IIS.TablCHast_4.Дом));
                }
            }
            
            /// <summary>
            /// "ДомL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДомL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДомL", typeof(IIS.TablCHast_4.Дом));
                }
            }
        }
    }
}
