//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TablCHast_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Улица.
    /// </summary>
    // *** Start programmer edit section *** (Улица CustomAttributes)

    // *** End programmer edit section *** (Улица CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УлицаE", new string[] {
            "Назв as \'Назв\'",
            "Дом as \'Дом\'",
            "Дом.Номер as \'Номер\'"}, Hidden=new string[] {
            "Дом.Номер"})]
    [MasterViewDefineAttribute("УлицаE", "Дом", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    public class Улица : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазв;
        
        private IIS.TablCHast_4.Дом fДом;
        
        private IIS.TablCHast_4.Ученик fУченик;
        
        // *** Start programmer edit section *** (Улица CustomMembers)

        // *** End programmer edit section *** (Улица CustomMembers)

        
        /// <summary>
        /// Назв.
        /// </summary>
        // *** Start programmer edit section *** (Улица.Назв CustomAttributes)

        // *** End programmer edit section *** (Улица.Назв CustomAttributes)
        [StrLen(255)]
        public virtual string Назв
        {
            get
            {
                // *** Start programmer edit section *** (Улица.Назв Get start)

                // *** End programmer edit section *** (Улица.Назв Get start)
                string result = this.fНазв;
                // *** Start programmer edit section *** (Улица.Назв Get end)

                // *** End programmer edit section *** (Улица.Назв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Улица.Назв Set start)

                // *** End programmer edit section *** (Улица.Назв Set start)
                this.fНазв = value;
                // *** Start programmer edit section *** (Улица.Назв Set end)

                // *** End programmer edit section *** (Улица.Назв Set end)
            }
        }
        
        /// <summary>
        /// Улица.
        /// </summary>
        // *** Start programmer edit section *** (Улица.Дом CustomAttributes)

        // *** End programmer edit section *** (Улица.Дом CustomAttributes)
        [PropertyStorage(new string[] {
                "Дом"})]
        [NotNull()]
        public virtual IIS.TablCHast_4.Дом Дом
        {
            get
            {
                // *** Start programmer edit section *** (Улица.Дом Get start)

                // *** End programmer edit section *** (Улица.Дом Get start)
                IIS.TablCHast_4.Дом result = this.fДом;
                // *** Start programmer edit section *** (Улица.Дом Get end)

                // *** End programmer edit section *** (Улица.Дом Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Улица.Дом Set start)

                // *** End programmer edit section *** (Улица.Дом Set start)
                this.fДом = value;
                // *** Start programmer edit section *** (Улица.Дом Set end)

                // *** End programmer edit section *** (Улица.Дом Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.TablCHast_4.Ученик.
        /// </summary>
        // *** Start programmer edit section *** (Улица.Ученик CustomAttributes)

        // *** End programmer edit section *** (Улица.Ученик CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Ученик"})]
        public virtual IIS.TablCHast_4.Ученик Ученик
        {
            get
            {
                // *** Start programmer edit section *** (Улица.Ученик Get start)

                // *** End programmer edit section *** (Улица.Ученик Get start)
                IIS.TablCHast_4.Ученик result = this.fУченик;
                // *** Start programmer edit section *** (Улица.Ученик Get end)

                // *** End programmer edit section *** (Улица.Ученик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Улица.Ученик Set start)

                // *** End programmer edit section *** (Улица.Ученик Set start)
                this.fУченик = value;
                // *** Start programmer edit section *** (Улица.Ученик Set end)

                // *** End programmer edit section *** (Улица.Ученик Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УлицаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УлицаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УлицаE", typeof(IIS.TablCHast_4.Улица));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Улица.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfУлица CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfУлица CustomAttributes)
    public class DetailArrayOfУлица : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.TablCHast_4.DetailArrayOfУлица members)

        // *** End programmer edit section *** (IIS.TablCHast_4.DetailArrayOfУлица members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Улица by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Улица.
        /// </summary>
        public DetailArrayOfУлица(IIS.TablCHast_4.Ученик fУченик) : 
                base(typeof(Улица), ((ICSSoft.STORMNET.DataObject)(fУченик)))
        {
        }
        
        public IIS.TablCHast_4.Улица this[int index]
        {
            get
            {
                return ((IIS.TablCHast_4.Улица)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.TablCHast_4.Улица dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
