//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TablCHast_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ученик.
    /// </summary>
    // *** Start programmer edit section *** (Ученик CustomAttributes)

    // *** End programmer edit section *** (Ученик CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УченикE", new string[] {
            "Назв as \'Назв\'"})]
    [AssociatedDetailViewAttribute("УченикE", "Улица", "УлицаE", true, "", "Улица", true, new string[] {
            ""})]
    [View("УченикL", new string[] {
            "Назв as \'Назв\'"})]
    public class Ученик : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазв;
        
        private IIS.TablCHast_4.DetailArrayOfУлица fУлица;
        
        // *** Start programmer edit section *** (Ученик CustomMembers)

        // *** End programmer edit section *** (Ученик CustomMembers)

        
        /// <summary>
        /// Назв.
        /// </summary>
        // *** Start programmer edit section *** (Ученик.Назв CustomAttributes)

        // *** End programmer edit section *** (Ученик.Назв CustomAttributes)
        [StrLen(255)]
        public virtual string Назв
        {
            get
            {
                // *** Start programmer edit section *** (Ученик.Назв Get start)

                // *** End programmer edit section *** (Ученик.Назв Get start)
                string result = this.fНазв;
                // *** Start programmer edit section *** (Ученик.Назв Get end)

                // *** End programmer edit section *** (Ученик.Назв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ученик.Назв Set start)

                // *** End programmer edit section *** (Ученик.Назв Set start)
                this.fНазв = value;
                // *** Start programmer edit section *** (Ученик.Назв Set end)

                // *** End programmer edit section *** (Ученик.Назв Set end)
            }
        }
        
        /// <summary>
        /// Ученик.
        /// </summary>
        // *** Start programmer edit section *** (Ученик.Улица CustomAttributes)

        // *** End programmer edit section *** (Ученик.Улица CustomAttributes)
        public virtual IIS.TablCHast_4.DetailArrayOfУлица Улица
        {
            get
            {
                // *** Start programmer edit section *** (Ученик.Улица Get start)

                // *** End programmer edit section *** (Ученик.Улица Get start)
                if ((this.fУлица == null))
                {
                    this.fУлица = new IIS.TablCHast_4.DetailArrayOfУлица(this);
                }
                IIS.TablCHast_4.DetailArrayOfУлица result = this.fУлица;
                // *** Start programmer edit section *** (Ученик.Улица Get end)

                // *** End programmer edit section *** (Ученик.Улица Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ученик.Улица Set start)

                // *** End programmer edit section *** (Ученик.Улица Set start)
                this.fУлица = value;
                // *** Start programmer edit section *** (Ученик.Улица Set end)

                // *** End programmer edit section *** (Ученик.Улица Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УченикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УченикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УченикE", typeof(IIS.TablCHast_4.Ученик));
                }
            }
            
            /// <summary>
            /// "УченикL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УченикL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УченикL", typeof(IIS.TablCHast_4.Ученик));
                }
            }
        }
    }
}
