//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TablCHast_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Школа.
    /// </summary>
    // *** Start programmer edit section *** (Школа CustomAttributes)

    // *** End programmer edit section *** (Школа CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ШколаE", new string[] {
            "Назв as \'Назв\'",
            "Ученик as \'Ученик\'",
            "Ученик.Назв as \'Назв\'"}, Hidden=new string[] {
            "Ученик.Назв"})]
    [MasterViewDefineAttribute("ШколаE", "Ученик", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Назв")]
    [View("ШколаL", new string[] {
            "Назв as \'Назв\'",
            "Ученик.Назв as \'Назв\'"})]
    public class Школа : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазв;
        
        private IIS.TablCHast_4.Ученик fУченик;
        
        // *** Start programmer edit section *** (Школа CustomMembers)

        // *** End programmer edit section *** (Школа CustomMembers)

        
        /// <summary>
        /// Назв.
        /// </summary>
        // *** Start programmer edit section *** (Школа.Назв CustomAttributes)

        // *** End programmer edit section *** (Школа.Назв CustomAttributes)
        [StrLen(255)]
        public virtual string Назв
        {
            get
            {
                // *** Start programmer edit section *** (Школа.Назв Get start)

                // *** End programmer edit section *** (Школа.Назв Get start)
                string result = this.fНазв;
                // *** Start programmer edit section *** (Школа.Назв Get end)

                // *** End programmer edit section *** (Школа.Назв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Школа.Назв Set start)

                // *** End programmer edit section *** (Школа.Назв Set start)
                this.fНазв = value;
                // *** Start programmer edit section *** (Школа.Назв Set end)

                // *** End programmer edit section *** (Школа.Назв Set end)
            }
        }
        
        /// <summary>
        /// Школа.
        /// </summary>
        // *** Start programmer edit section *** (Школа.Ученик CustomAttributes)

        // *** End programmer edit section *** (Школа.Ученик CustomAttributes)
        [PropertyStorage(new string[] {
                "Ученик"})]
        [NotNull()]
        public virtual IIS.TablCHast_4.Ученик Ученик
        {
            get
            {
                // *** Start programmer edit section *** (Школа.Ученик Get start)

                // *** End programmer edit section *** (Школа.Ученик Get start)
                IIS.TablCHast_4.Ученик result = this.fУченик;
                // *** Start programmer edit section *** (Школа.Ученик Get end)

                // *** End programmer edit section *** (Школа.Ученик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Школа.Ученик Set start)

                // *** End programmer edit section *** (Школа.Ученик Set start)
                this.fУченик = value;
                // *** Start programmer edit section *** (Школа.Ученик Set end)

                // *** End programmer edit section *** (Школа.Ученик Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ШколаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ШколаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ШколаE", typeof(IIS.TablCHast_4.Школа));
                }
            }
            
            /// <summary>
            /// "ШколаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ШколаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ШколаL", typeof(IIS.TablCHast_4.Школа));
                }
            }
        }
    }
}
